### ISSUE TITLE
use kaminari/will_paginate

### ISSUE THREAD

**Issue by ajb** [dobtco/filterer#11]

**Comment by olliebennett** [comment]
Can the `chain` method be used to integrate with [kaminari](https://github.com/amatsuda/kaminari)?

I also back this feature request as the `filterer` gem - while fantastic for managing filters - is let down by its pagination logic (specifically the view helper).

If it's not possible to integrate kaminari (or will-paginate), I could attempt to improve the pagination logic within this gem.

**Comment by olliebennett** [comment]
I believe the following is the appropriate way to integrate kaminari:

```ruby
# Without Kaminari:
@filterer = PersonFilterer.new(params)
# With Kaminari:
@filterer = PersonFilterer.chain(params).page(params[:page]).per(100)
```

And the respective change in the view:

```ruby
# Without Kaminari:
@filterer.results.each do |person|
# With Kaminari:
@filterer.each do |person|
```

If this is indeed the most appropriate solution, is there a need for this issue to remain open? If you'd like, I can add a quick note to the README highlighting this usage.

**Comment by ajb** [comment]
Hey @olliebennett,

Yes, that workaround will work for now. The reason this issue is open is that I'm planning to remove the current pagination methods/views and make usage of kaminari/will_paginate the primary method for pagination.

**Comment by olliebennett** [comment]
Great - thanks for the response. Should the 'sort' options be obeyed when using Kaminari in the above manner? In my trials the `sort` (and `direction`) params are ignored. I believe this is due to [the following code](https://github.com/dobtco/filterer/blob/9e19f44e967780ae40c0bd51a7faf167165e0418/lib/filterer/base.rb#L90) in `base.rb`:

```ruby
def find_results
  @results = opts.delete(:starting_query) || starting_query
  add_params_to_query
  return if @opts[:chainable]
  order_results
```

Would it be a problem to move `order_results` above the `chainable` check? Perhaps (in order to preserve backwards compatibility) we could have a new `chain_with_ordering` method or pass a new `:include_ordering` option?

If there are no obvious pitfalls with this that you can see, I can attempt to provide a PR for this. Can continue discussion in a separate issue if you prefer? Thanks again

**Comment by ajb** [comment]
> I believe this is due to the following code in base.rb:

Yeah, tbh I don't really remember why the code works that way. I'm :+1: on adding an `include_ordering` option until the next major release.

**Comment by ajb** [comment]
This will be released in 1.0.0.

**Comment by ramontayag** [comment]
Great - thanks!

**Comment by ajb** [comment]
Hi all,

I just pushed `1.0.0.beta.1` to Rubygems. If you have a chance to take a look, maybe read the documentation, and provide some feedback, it would be super helpful!
